sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources: &commonsources
    packages: &commonpackages
    - cmake
    - cmake-data
    - doxygen
    - texlive-base
    - python-virtualenv
    - python-pytest
    # avoid installing fusion
    - libboost-system1.55-dev
    - libboost-thread1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-date-time1.55-dev
    - libboost-timer1.55-dev
    - libboost-chrono1.55-dev
    - python-pip
    - libtbb-dev
    - ccache
    - libsuitesparse-dev
    - lcov
    - curl
    - ninja-build
    - python3-requests

before_install:
  - |-
    : ${OPTS:="config.opts/travis.ninja"} && export OPTS
  - |-
    : ${BUILD_CMD:="ninja -k 10000 -j 2"} && export BUILD_CMD
  # workaround for https://github.com/travis-ci/travis-ci/issues/5285
  - sudo -E apt-get install -y -q libtbb-dev python-pip libmetis-dev python3-pip libfftw3-mpi-dev libfftw3-bin libfftw3-dev libopenmpi-dev
  - sudo -E pip3 install virtualenv cpp-coveralls
  - sudo -E pip install virtualenv cpp-coveralls
  - export PATH=/usr/lib/ccache:$PATH
  - cd $HOME
  - test -d src || git clone https://github.com/wwu-numerik/dune-multiscale-super.git src
  - git submodule update --init --recursive
  - git submodule status
  - cd $HOME/src
  - ls -lh $PWD
  - ls -lh scripts/
  - ls -lh scripts/bash/
  - ./scripts/bash/travis_prepare_compiler_setup.sh
  - export DCTRL_ARG="--builddir=${DUNE_BUILD_DIR}  --opts=${OPTS}"
  # our local scripts look for an OPTS env entry
  - ./local/bin/download_external_libraries.py
  - ./local/bin/build_external_libraries.py
  # ensures ${MY_MODULE} from travis own checkout is used
  - echo removing modules ${MODULES_TO_DELETE}
  - rm -rf ${MODULES_TO_DELETE} ${MY_MODULE}

# command to install dependencies
install:
  - cd $HOME/src
  - export SRC_DCTRL=$PWD/dune-common/bin/dunecontrol
  - ${SRC_DCTRL} ${DCTRL_ARG} --only=dune-common all
  - cat ${DUNE_BUILD_DIR}/dune-common/CMakeFiles/CMake*log
  - ${SRC_DCTRL} ${DCTRL_ARG} all
  - ${SRC_DCTRL} ${DCTRL_ARG} all
  # move my travis checkout into this source tree
  - cp -ra ${TRAVIS_BUILD_DIR} .

before_script:
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} configure
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD}
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} test_binaries

script:
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} test
    # retry this step because of the implicated race condition in cloning an pushing with multiple builder running in parallel
    - travis_retry $HOME/src/scripts/bash/travis_upload_test_logs.bash ${DUNE_BUILD_DIR}/${MY_MODULE}/dune/multiscale/*/test/

    - PYTHONPATH=$HOME/src/scripts/python/ python3 -c "import travis_report as tp; tp.clang_format_status(\"${TRAVIS_BUILD_DIR}\")"
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} headercheck
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} install | grep -v "Installing"
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ${BUILD_CMD} package_source

# runs independent of 'script' failure/success
after_script:
    # reset for ctest
    - ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec make clean
    - export CTEST_ARG="--output-on-failure -S ${TRAVIS_BUILD_DIR}/.travis.ctest"
    # ctest errors on coverage gathering, this should NOT fail our entire build
    #- ${SRC_DCTRL} ${DCTRL_ARG} --only=${MY_MODULE} bexec ctest ${CTEST_ARG} || echo "CTest Failed"

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - MY_MODULE=dune-mlmc GCCDEFAULT=4.9 DUNE_BUILD_DIR=${HOME}/dune_build/ INSTALL_DIR=$HOME/dune CTEST_OUTPUT_ON_FAILURE=1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources:
          - *commonsources
          packages:
          - *commonpackages
      env: CXX=g++ CC=gcc 

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - *commonsources
          packages:
          - *commonpackages
          - ['ubuntu-toolchain-r-test'] 
          - ['g++-5', 'gcc-5']
      env: CXX=g++-5 CC=gcc-5 

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - *commonsources
          - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
          - *commonpackages
          - ['clang-3.7']
      env: CXX=clang++-3.7 CC=clang-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - *commonsources
          - ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages:
          - *commonpackages
          - ['clang-3.7']
      env: OPTS=config.opts/travis.make BUILD_CMD="make -k -j2" CXX=clang++-3.7 CC=clang-3.7 

    #- os: linux
      #compiler: clang
      #addons:
        #apt:
          #sources:
          #- *commonsources
          #- ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          #packages:
          #- *commonpackages
          #- ['clang-3.8']
      #env: CXX_COMPILER=clang++-3.8 COMPILER=clang-3.8
